// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: packet.proto

/*
Package packet is a generated protocol buffer package.

It is generated from these files:
	packet.proto

It has these top-level messages:
	Packet
*/
package packet

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Packet struct {
	// Type
	Type uint64 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	// Any the inside packet
	Message *google_protobuf.Any `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *Packet) Reset()                    { *m = Packet{} }
func (m *Packet) String() string            { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()               {}
func (*Packet) Descriptor() ([]byte, []int) { return fileDescriptorPacket, []int{0} }

func (m *Packet) GetType() uint64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Packet) GetMessage() *google_protobuf.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*Packet)(nil), "packet.Packet")
}

func init() { proto.RegisterFile("packet.proto", fileDescriptorPacket) }

var fileDescriptorPacket = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x4c, 0xce,
	0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0xa4, 0x38, 0x13, 0xf3,
	0x2a, 0x21, 0x42, 0x4a, 0x3e, 0x5c, 0x6c, 0x01, 0x60, 0x41, 0x21, 0x21, 0x2e, 0x96, 0x92, 0xca,
	0x82, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x30, 0x5b, 0x48, 0x8f, 0x8b, 0x3d, 0x37,
	0xb5, 0xb8, 0x38, 0x31, 0x3d, 0x55, 0x82, 0x59, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x44, 0x2f, 0x3d,
	0x3f, 0x3f, 0x3d, 0x27, 0x15, 0xa2, 0x3b, 0xa9, 0x34, 0x4d, 0xcf, 0x31, 0xaf, 0x32, 0x08, 0xa6,
	0x28, 0x89, 0x0d, 0x2c, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x05, 0xb2, 0xbb, 0xfd, 0x77,
	0x00, 0x00, 0x00,
}
