// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: packet.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	packet.proto

It has these top-level messages:
	Packet
*/
package network

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Packet struct {
	Type uint64 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	// To define the a unique connection
	UUID string `protobuf:"bytes,2,opt,name=UUID,json=uUID,proto3" json:"UUID,omitempty"`
	// Any the inside packet
	Message *google_protobuf.Any `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *Packet) Reset()                    { *m = Packet{} }
func (m *Packet) String() string            { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()               {}
func (*Packet) Descriptor() ([]byte, []int) { return fileDescriptorPacket, []int{0} }

func (m *Packet) GetType() uint64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Packet) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Packet) GetMessage() *google_protobuf.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*Packet)(nil), "pb.Packet")
}

func init() { proto.RegisterFile("packet.proto", fileDescriptorPacket) }

var fileDescriptorPacket = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x4c, 0xce,
	0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x92, 0xe2, 0x4c, 0xcc,
	0xab, 0x84, 0x70, 0x95, 0x12, 0xb8, 0xd8, 0x02, 0xc0, 0xd2, 0x42, 0x42, 0x5c, 0x2c, 0x25, 0x95,
	0x05, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x60, 0x36, 0x48, 0x2c, 0x34, 0xd4, 0xd3,
	0x45, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x88, 0xa5, 0x34, 0xd4, 0xd3, 0x45, 0x48, 0x8f, 0x8b,
	0x3d, 0x37, 0xb5, 0xb8, 0x38, 0x31, 0x3d, 0x55, 0x82, 0x59, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x44,
	0x2f, 0x3d, 0x3f, 0x3f, 0x3d, 0x27, 0x15, 0x62, 0x62, 0x52, 0x69, 0x9a, 0x9e, 0x63, 0x5e, 0x65,
	0x10, 0x4c, 0x51, 0x12, 0x1b, 0x58, 0xd8, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x23, 0x4a, 0xcb,
	0x98, 0x87, 0x00, 0x00, 0x00,
}
